name: Build FAP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      id: install_latest_nightly
      with:
        toolchain: nightly
        override: true
        target: thumbv7em-none-eabihf

    - name: Build library
      uses: actions-rs/cargo@v1
      id: build_library
      with:
        command: build
        args: --release

    - name: Build FAP
      uses: oleksiikutuzov/flipperzero-ufbt-action@v1
      id: build_fap
      with:
        channel: release
        path: res

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
      if: startsWith(github.ref, 'refs/tags/v')

    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./flipper_serprog.fap
        asset_name: flipper_serprog.fap
        asset_content_type: application/octet-stream
      if: startsWith(github.ref, 'refs/tags/v')
