name: Build FAP

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v3

    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      id: install_latest_nightly
      with:
        toolchain: nightly
        override: true
        target: thumbv7em-none-eabihf

    - name: Build binary
      uses: actions-rs/cargo@v1
      id: build_library
      with:
        command: build
        args: --release
    
    - name: Tag Release
      id: tag_release
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      if: github.ref == 'refs/heads/main'
  
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_release.outputs.new_tag }}
        release_name: Release ${{ steps.tag_release.outputs.new_tag }}
        body: ${{ steps.tag_release.outputs.changelog }}
        draft: false
        prerelease: false
      if: github.ref == 'refs/heads/main'
  
    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/thumbv7em-none-eabihf/release/flipper_serprog
        asset_name: flipper_serprog.fap
        asset_content_type: application/octet-stream
      if: github.ref == 'refs/heads/main'
